"""
slack_notify.py — Slack notification for GM Daily Briefing
Austin Proper Hotel · Anis Khoury

Sends the daily GM briefing to Slack via webhook or API.
Configure SLACK_WEBHOOK_URL or SLACK_BOT_TOKEN + SLACK_CHANNEL in environment.
"""

import os
import json
import urllib.request
import urllib.error
from datetime import date


SLACK_WEBHOOK_URL = os.environ.get('SLACK_WEBHOOK_URL')
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN')
SLACK_CHANNEL = os.environ.get('SLACK_CHANNEL', '#gm-briefing')
SLACK_DM_USER_ID = os.environ.get('SLACK_DM_USER_ID')  # For DM delivery


def format_briefing_for_slack(summary: dict, gaps: list, today_events: list = None) -> list:
    """
    Format the GM briefing as Slack blocks for rich display.
    Returns a list of Slack block kit elements.
    """
    today_str = date.today().isoformat()

    s30 = summary.get('30d', {})
    s7 = summary.get('7d', {})

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"☀️ GM Daily Briefing — {today_str}",
                "emoji": True
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Austin Proper Hotel* · Anis Khoury"
            }
        },
        {"type": "divider"},
    ]

    # 7-day snapshot
    if s7:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*📊 Last 7 Days*\n"
                    f"• Total hours tracked: *{s7.get('total_h', 0)}h*\n"
                    f"• Meetings: *{s7.get('total_meeting_h', 0)}h* ({s7.get('meeting_h_per_wk', 0)}h/wk)\n"
                    f"• Solo work: *{s7.get('total_solo_h', 0)}h* ({s7.get('solo_h_per_wk', 0)}h/wk)\n"
                    f"• Utilization: *{s7.get('pct_of_60h', 0)}%* of 60h week"
                )
            }
        })

    # Top categories this week
    if s7 and s7.get('by_category'):
        top_cats = sorted(
            [(k, v) for k, v in s7['by_category'].items() if v.get('hours', 0) > 0],
            key=lambda x: x[1]['hours'],
            reverse=True
        )[:5]

        if top_cats:
            cat_lines = "\n".join([
                f"• {cat}: *{data['hours']}h* ({data['count']} events)"
                for cat, data in top_cats
            ])
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*🏆 Top Categories (7d)*\n{cat_lines}"
                }
            })

    blocks.append({"type": "divider"})

    # Today's schedule preview
    if today_events:
        meeting_count = len([e for e in today_events if e.get('block_type') == 'meeting'])
        solo_count = len([e for e in today_events if e.get('block_type') == 'solo_work'])

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📅 Today's Schedule*\n• {meeting_count} meetings\n• {solo_count} solo blocks"
            }
        })

    # Gaps requiring attention
    today_gaps = [g for g in gaps if g.get('date') == today_str]
    if today_gaps:
        gap_text = "\n".join([
            f"• {g['start']}–{g['end']} ({g['duration_min']} min)"
            for g in today_gaps[:3]
        ])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*⚠️ Unblocked Gaps Today*\n{gap_text}"
            }
        })

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "Generated by Austin Proper GM Report System"
            }
        ]
    })

    return blocks


def send_to_slack(blocks: list, text_fallback: str = "GM Daily Briefing") -> bool:
    """
    Send message to Slack via webhook or Bot API.
    Returns True on success, False on failure.
    """
    if SLACK_WEBHOOK_URL:
        return _send_via_webhook(blocks, text_fallback)
    elif SLACK_BOT_TOKEN:
        return _send_via_api(blocks, text_fallback)
    else:
        print("⚠️  Slack not configured. Set SLACK_WEBHOOK_URL or SLACK_BOT_TOKEN.")
        return False


def _send_via_webhook(blocks: list, text_fallback: str) -> bool:
    """Send via incoming webhook."""
    payload = {
        "text": text_fallback,
        "blocks": blocks
    }

    try:
        req = urllib.request.Request(
            SLACK_WEBHOOK_URL,
            data=json.dumps(payload).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 200:
                print("✓ Slack notification sent via webhook")
                return True
    except urllib.error.HTTPError as e:
        print(f"✗ Slack webhook error: {e.code} {e.reason}")
    except urllib.error.URLError as e:
        print(f"✗ Slack webhook connection error: {e.reason}")
    except Exception as e:
        print(f"✗ Slack webhook error: {e}")

    return False


def _send_via_api(blocks: list, text_fallback: str) -> bool:
    """Send via Slack Web API (chat.postMessage)."""
    channel = SLACK_DM_USER_ID or SLACK_CHANNEL

    payload = {
        "channel": channel,
        "text": text_fallback,
        "blocks": blocks
    }

    try:
        req = urllib.request.Request(
            "https://slack.com/api/chat.postMessage",
            data=json.dumps(payload).encode('utf-8'),
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {SLACK_BOT_TOKEN}'
            }
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            if result.get('ok'):
                print(f"✓ Slack notification sent to {channel}")
                return True
            else:
                print(f"✗ Slack API error: {result.get('error', 'unknown')}")
    except urllib.error.HTTPError as e:
        print(f"✗ Slack API error: {e.code} {e.reason}")
    except urllib.error.URLError as e:
        print(f"✗ Slack API connection error: {e.reason}")
    except Exception as e:
        print(f"✗ Slack API error: {e}")

    return False


def send_briefing(summary_file: str = 'calendar_summary.json',
                  gaps_file: str = 'calendar_gaps.json',
                  events_file: str = 'calendar_categorized.json') -> bool:
    """
    Load data and send the GM briefing to Slack.
    """
    try:
        with open(summary_file) as f:
            summary = json.load(f)
        with open(gaps_file) as f:
            gaps = json.load(f)

        today_events = []
        try:
            with open(events_file) as f:
                all_events = json.load(f)
                today_str = date.today().isoformat()
                today_events = [e for e in all_events if e.get('date_local') == today_str]
        except Exception:
            pass

        blocks = format_briefing_for_slack(summary, gaps, today_events)
        return send_to_slack(blocks)

    except FileNotFoundError as e:
        print(f"✗ Missing data file: {e.filename}")
        return False
    except json.JSONDecodeError as e:
        print(f"✗ Invalid JSON: {e}")
        return False


if __name__ == '__main__':
    send_briefing()
